language: cpp

# compiler:
# - gcc
# - clang

env:
- ENABLE_CPPUNIT=true
- ENABLE_CPPUNIT=false

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.7

matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.7
    env: COMPILER=g++-4.7

before_install:
#- sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
#- sudo apt-get update -qq
#- sudo apt-get build-dep libtorrent-dev

#  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.7; fi
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi

  - if $ENABLE_CPPUNIT; then sudo apt-get install libcppunit-dev; fi

# Figure out how to fix the issue running 'make check'.
script: ./autogen.sh && ./configure && make -j12 check && sudo make install
