language: cpp

matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages:
        - g++-4.7
    env: COMPILER=g++-4.7
  - compiler: gcc
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages:
        - g++-4.7
        - libcppunit-dev
    env: COMPILER=g++-4.7
  - compiler: clang
    env: COMPILER=clang++
  - compiler: clang
    addons:
      apt:
        packages:
        - libcppunit-dev
    env: COMPILER=clang++

script:
- ./autogen.sh
- CXX="$COMPILER" ./configure
- make -j12 check
- sudo make install
